services:
  mongo:
    image: mongo:7
    container_name: base-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend/go
    container_name: base-api
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=base
      - MONGO_USERS_COLLECTION=users
    depends_on:
      - mongo
    ports:
      - "8080:8080"

volumes:
  mongo_data:
